### ISSUE TITLE
Web | Stylus

### ISSUE THREAD

**Issue by ww522413622** [ww522413622/blog#15]
## Description
在 Sass 和 Less 中脱引而出的选择。

## TODO List
- [x] [Stylus 编码规范](https://github.com/CMUI/doc/issues/1)
- [x] [对比学习 sass 和 stylus 的常用功能](https://segmentfault.com/a/1190000008013566)
- [x] [再谈 CSS 预处理器](http://blog.csdn.net/u013063153/article/details/52485993)
- [x] [stylus 入门使用方法](https://segmentfault.com/a/1190000002712872)
- [x] [CSS 预处理器比较](https://juejin.im/entry/58466cac61ff4b006ba71ee1)

### 终端指令
```bash
-u, --use <path> 指定路径中的插件
-w, --watch 观察代码变更实时更新
-o, --out <dir> 指定输出路径
-C, --css <src> [dest] 把 CSS 转换成简洁的 Stylus
-I, --include <path>    Add <path> to lookup paths
-c, --compress 压缩输出文件
-l, --line-numbers 在生成的 CSS 中显示 Stylus 文件名以及行数
-V, --version 输出版本
-h, --help 帮助
```

**Comment by ww522413622** [comment]
后续总结归纳~
