### ISSUE TITLE
BootStrap | 源码学习

### ISSUE THREAD

**Issue by ww522413622** [ww522413622/blog#24]
## Description
看看规范、看看样式代码如何实现优雅复用。

## TODO List
- [ ] alerts.scss
- [ ] badges.scss
- [ ] breadcrumbs.scss
- [ ] button-groups.scss
- [ ] buttons.scss
- [ ] carousel.scss
- [ ] close.scss
- [ ] code.scss
- [ ] component-animations.scss
- [ ] dropdowns.scss
- [ ] forms.scss
- [ ] glyphicons.scss
- [ ] grid.scss
- [ ] input-groups.scss
- [ ] jumbotron.scss
- [ ] labels.scss
- [ ] list-group.scss
- [ ] media.scss
- [ ] mixins.scss
- [ ] modals.scss
- [ ] navbar.scss
- [ ] navs.scss
- [ ] normalize.scss
- [ ] pager.scss
- [ ] pagination.scss
- [ ] panels.scss
- [ ] popovers.scss
- [ ] print.scss
- [ ] progress-bars.scss
- [ ] responsive-embed.scss
- [ ] responsive-utilities.scss
- [ ] scaffolding.scss
- [ ] tables.scss
- [ ] theme.scss
- [ ] thumbnails.scss
- [ ] tooltip.scss
- [ ] type.scss
- [ ] utilities.scss
- [ ] variables.scss
- [ ] wells.scss

mixins
- [ ] alerts.scss
- [ ] background-variant.scss
- [ ] border-radius.scss
- [ ] buttons.scss
- [ ] center-block.scss
- [ ] clearfix.scss
- [ ] forms.scss
- [ ] gradients.scss
- [ ] grid-framework.scss
- [ ] grid.scss
- [ ] hide-text.scss
- [ ] image.scss
- [ ] labels.scss
- [ ] list-group.scss
- [ ] nav-divider.scss
- [ ] nav-vertical-align.scss
- [ ] opacity.scss
- [ ] pagination.scss
- [ ] panels.scss
- [ ] progress-bar.scss
- [ ] reset-filter.scss
- [ ] reset-text.scss
- [ ] resize.scss
- [ ] responsive-visibility.scss
- [ ] size.scss
- [ ] tab-focus.scss
- [ ] table-row.scss
- [ ] text-emphasis.scss
- [ ] text-overflow.scss
