### ISSUE TITLE
Github | 常规操作

### ISSUE THREAD

**Issue by ww522413622** [ww522413622/blog#5]
## Description
学习如何优雅的使用 Github

## TODO List
- [x] [开源项目美化](http://www.jianshu.com/p/ae6749858f28)
- [x] [图片标签](http://blog.csdn.net/yangbodong22011/article/details/51791085)
- [x] [版本控制入门](http://www.imooc.com/learn/390)
- [x] [全面认识](https://www.kancloud.cn/thinkphp/github-tips/37873)
- [x] [Github 周边](https://github.com/marketplace)
- [x] [Github 实现 GTD](https://sspai.com/post/39872)

**Comment by ww522413622** [comment]
深有感触，用了一年半的github还有这么多玩法😂，以后一一实践在项目中。
